import type { HandoffRecord, TaskRecord } from '../db/index.js';
import { bulletList, codeBulletList } from './markdown.js';

/** Render a human-readable HANDOFF.md for a task and its latest handoff. */
export function renderHandoffMarkdown(task: TaskRecord, handoff: HandoffRecord): string {
  return [
    `# Handoff: ${task.taskId} — ${task.title}`,
    '',
    `**Status:** ${handoff.status}`,
    `**Agent:** ${task.agent ?? 'unknown'}`,
    `**Branch:** ${task.branch ?? 'unknown'}`,
    '',
    '## What changed',
    '',
    handoff.whatChanged,
    '',
    '## Changed files',
    '',
    codeBulletList(handoff.changedFiles),
    '',
    '## Tests run',
    '',
    codeBulletList(handoff.testsRun),
    '',
    '## Assumptions',
    '',
    bulletList(handoff.assumptions),
    '',
    '## Decisions',
    '',
    bulletList(handoff.decisions),
    '',
    '## Known risks',
    '',
    bulletList(handoff.knownRisks),
    '',
    '## Guardrails checked',
    '',
    bulletList(handoff.guardrailsChecked),
    '',
    '## Needs review from',
    '',
    bulletList(handoff.needsReviewFrom),
    '',
    '## Next steps',
    '',
    bulletList(handoff.nextSteps),
    '',
  ].join('\n');
}
